
["Global Settings"]
	enable = true

["Attribute 1"]
	enable = true
	display_name = "Â§fHealth Â§4â™¥ Â§f| Â§4"
	attribute_namespace = "minecraft"
	attribute_name = "generic.max_health"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 2"]
	enable = true
	display_name = "Â§fDamage Â§câš” Â§f| Â§c"
	attribute_namespace = "minecraft"
	attribute_name = "generic.attack_damage"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 3"]
	enable = true
	display_name = "Â§fAS Â§eâŒ› Â§f| Â§e"
	attribute_namespace = "minecraft"
	attribute_name = "generic.attack_speed"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 4"]
	enable = true
	display_name = "Â§fArmor Â§bğŸ›¡ Â§f| Â§b"
	attribute_namespace = "minecraft"
	attribute_name = "generic.armor"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 5"]
	enable = true
	display_name = "Â§fMS Â§ağŸƒ Â§f| Â§a"
	attribute_namespace = "minecraft"
	attribute_name = "generic.movement_speed"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 100.0

["Attribute 6"]
	enable = true
	display_name = "Â§fKnock Res Â§8ğŸ›‘ Â§f| Â§8"
	attribute_namespace = "minecraft"
	attribute_name = "generic.knockback_resistance"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 10.0

["Attribute 7"]
	enable = true
	display_name = "Â§fToughness Â§9ğŸ’ª Â§f| Â§9"
	attribute_namespace = "minecraft"
	attribute_name = "generic.armor_toughness"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 8"]
	enable = true
	display_name = "Â§fLuck Â§dğŸ€ Â§f| Â§d"
	attribute_namespace = "minecraft"
	attribute_name = "generic.luck"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 9"]
	enable = false
	display_name = "Â§fHealth : "
	attribute_namespace = "minecraft"
	attribute_name = "generic.max_health"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 10"]
	enable = false
	display_name = "Â§fHealth : "
	attribute_namespace = "minecraft"
	attribute_name = "generic.max_health"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 11"]
	enable = false
	display_name = "Â§fHealth : "
	attribute_namespace = "minecraft"
	attribute_name = "generic.max_health"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 12"]
	enable = false
	display_name = "Â§fHealth : "
	attribute_namespace = "minecraft"
	attribute_name = "generic.max_health"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 13"]
	enable = false
	display_name = "Â§fHealth : "
	attribute_namespace = "minecraft"
	attribute_name = "generic.max_health"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 14"]
	enable = false
	display_name = "Â§fHealth : "
	attribute_namespace = "minecraft"
	attribute_name = "generic.max_health"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

["Attribute 15"]
	enable = false
	display_name = "Â§fHealth : "
	attribute_namespace = "minecraft"
	attribute_name = "generic.max_health"
	#changes how to the attribute value displays when you hover (value * modifer)
	display_modifer = 1.0

